; This is an .INI file, used as a simple way to tune a game without recompiling/hardcoding it.
; A great place for gameplay variables and more. Another example of data-driven programming. 

[init]
vertexShaderPath=../Assets/Shaders/LevelVertex.hlsl
fragmentShaderPath=../Assets/Shaders/LevelPixel.hlsl